import 'reflect-metadata'
import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import SocialsColumn from './socials_column';

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oghenefejiro Abohweyere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body className={`${lora.className} bg-[#394D74]`}>

        {children}


        <div className='absolute m-auto right-[20px] top-[50%] translate-y-[-50%]'>
          <SocialsColumn />
        </div>
      </body>

    </html>
  );
}
